In [20]:
import tensorflow as tf

print(tf.enable_eager_execution())

None


In [3]:
print(tf.add(1, 2))
print(tf.add([1, 2], [3, 4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2, 3]))
print(tf.encode_base64('hello world'))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(b'aGVsbG8gd29ybGQ', shape=(), dtype=string)


In [4]:
print(tf.square(2) + tf.square(3))

tf.Tensor(13, shape=(), dtype=int32)


In [5]:
x = tf.matmul([[1]], [[2, 3]])
print(x.shape)
print(x.dtype)

(1, 2)
<dtype: 'int32'>


In [6]:
print(x)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)


In [26]:
import numpy as np
ndarray = np.ones([3,3])
tensor = tf.multiply(ndarray,42)
print(tensor)

tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)


In [8]:
print(np.add(tensor,1))

[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]


In [9]:
print(tensor.numpy())

[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


In [28]:
x = tf.random_uniform([3,3])
print(tf.test.is_gpu_available())
print(x.device.endswith('GPU:0'))

False
False


In [12]:
# force execution on CPU
print('On CPU:')
with tf.device('CPU:0'):
    x = tf.random_uniform([1000,1000])
    assert x.device.endswith('CPU:0')
    %timeit tf.matmul(x,x)

On CPU:


13.6 ms ± 240 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [27]:
# force execution on GPU
if tf.test.is_gpu_available():
    with tf.device('GPU:0'):
        x = tf.random_uniform([1000, 1000])
        assert x.device.endswith('GPU:0')
        % timeit tf.matmul(x, x)